In [1]:
#1 
import numpy as np

In [8]:
#2
np.__version__

'1.24.3'

In [12]:
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/krish/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/krish/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/krish/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/krish/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/krish/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/krish/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/krish/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/krish/anaconda3\\Lib

In [23]:
#3
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
#4
arr.itemsize * arr.size

80

In [38]:
#5
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [40]:
#6
arr1 = np.zeros(10)
arr1[4] = 1
arr1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [85]:
#7
arr2 = np.arange(10, 50)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [86]:
#8
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = arr3[::-1]

In [47]:
arr4

array([5, 4, 3, 2, 1])

In [48]:
#9
arr5 = np.arange(0,9)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
arr5 = arr5.reshape(3, 3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
#10
arr6 = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr6)

(array([0, 1, 4], dtype=int64),)

In [88]:
#11
arr7 = np.eye(3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
#12
arr8 = np.random.random((27))
arr8

array([0.97306165, 0.40646774, 0.5174785 , 0.30366107, 0.79452164,
       0.59684443, 0.86705088, 0.43986228, 0.27321175, 0.36138902,
       0.91214131, 0.03591265, 0.37761674, 0.85180963, 0.30153452,
       0.6992069 , 0.6275238 , 0.87823267, 0.5678798 , 0.14378074,
       0.17286262, 0.76461585, 0.63525911, 0.67646967, 0.26712587,
       0.7292687 , 0.66895227])

In [65]:
arr8 = arr8.reshape(3, 3, 3)
arr8

array([[[0.45693229, 0.98771697, 0.45619289],
        [0.87282832, 0.23319645, 0.76255323],
        [0.41336136, 0.0551491 , 0.77987041]],

       [[0.00903204, 0.79696969, 0.11927826],
        [0.48672207, 0.8863166 , 0.58210238],
        [0.02951106, 0.05707868, 0.42642459]],

       [[0.84090925, 0.83888493, 0.79171362],
        [0.8974214 , 0.82146718, 0.79960855],
        [0.71629971, 0.26639039, 0.75188975]]])

In [66]:
#13
arr9 = np.random.random(100)
arr9

array([0.26254674, 0.19948339, 0.02691077, 0.85374023, 0.00801964,
       0.60807864, 0.68339299, 0.0302251 , 0.10777447, 0.2326101 ,
       0.4582069 , 0.54633277, 0.37071686, 0.89816081, 0.61775787,
       0.45433281, 0.55756832, 0.55708012, 0.61608931, 0.0668593 ,
       0.96699199, 0.91684983, 0.32512609, 0.73043967, 0.29317195,
       0.4467746 , 0.33592892, 0.84924764, 0.89450417, 0.51800741,
       0.8914729 , 0.14730073, 0.41252077, 0.69830912, 0.44415101,
       0.73469821, 0.5114927 , 0.44106802, 0.43524366, 0.87916688,
       0.76772669, 0.17358154, 0.33880206, 0.31442399, 0.61353433,
       0.32124895, 0.43429075, 0.71386926, 0.05164767, 0.22464142,
       0.21369488, 0.19719469, 0.76986359, 0.07212948, 0.59468664,
       0.85087013, 0.53946164, 0.31066232, 0.64823956, 0.61322909,
       0.20372764, 0.79553083, 0.82343638, 0.98870148, 0.36294443,
       0.59306385, 0.02309364, 0.94794554, 0.10980209, 0.57841782,
       0.34772672, 0.2973926 , 0.88325901, 0.62375277, 0.26402

In [67]:
arr9.reshape(10, 10)

array([[0.26254674, 0.19948339, 0.02691077, 0.85374023, 0.00801964,
        0.60807864, 0.68339299, 0.0302251 , 0.10777447, 0.2326101 ],
       [0.4582069 , 0.54633277, 0.37071686, 0.89816081, 0.61775787,
        0.45433281, 0.55756832, 0.55708012, 0.61608931, 0.0668593 ],
       [0.96699199, 0.91684983, 0.32512609, 0.73043967, 0.29317195,
        0.4467746 , 0.33592892, 0.84924764, 0.89450417, 0.51800741],
       [0.8914729 , 0.14730073, 0.41252077, 0.69830912, 0.44415101,
        0.73469821, 0.5114927 , 0.44106802, 0.43524366, 0.87916688],
       [0.76772669, 0.17358154, 0.33880206, 0.31442399, 0.61353433,
        0.32124895, 0.43429075, 0.71386926, 0.05164767, 0.22464142],
       [0.21369488, 0.19719469, 0.76986359, 0.07212948, 0.59468664,
        0.85087013, 0.53946164, 0.31066232, 0.64823956, 0.61322909],
       [0.20372764, 0.79553083, 0.82343638, 0.98870148, 0.36294443,
        0.59306385, 0.02309364, 0.94794554, 0.10980209, 0.57841782],
       [0.34772672, 0.2973926 , 0.8832590

In [68]:
arr9.max()

0.9887014791745831

In [69]:
arr9.min()

0.008019635465411512

In [72]:
#14
arr10 = np.random.random(30)
arr10

array([0.88181695, 0.75312908, 0.94681473, 0.84700203, 0.52911268,
       0.90967378, 0.11892705, 0.636394  , 0.11407348, 0.55041448,
       0.15873626, 0.45125703, 0.85392356, 0.66467493, 0.77556175,
       0.07096794, 0.4434377 , 0.0973192 , 0.74999262, 0.73495502,
       0.11850631, 0.95035917, 0.52646392, 0.70451007, 0.61066663,
       0.14579095, 0.34148272, 0.158742  , 0.99685174, 0.01406723])

In [73]:
arr10.mean()

0.5285208331422017

In [99]:
#15
arr11 = np.ones((4, 4))
arr11[1:-1, 1:-1] = 0
arr11

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [82]:
#16
help(np.insert())

TypeError: insert() missing 3 required positional arguments: 'arr', 'obj', and 'values'

In [103]:
arr12 = np.random.random((4,4))

In [102]:
np.info(np.pad)

 pad(array, pad_width, mode='constant', **kwargs)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
    for each axis.
    ``(before, after)`` or ``((before, after),)`` yields same before
    and after pad for each axis.
    ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
    for all axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or par

In [109]:
np.pad(arr12, 1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.65794883, 0.96072628, 0.2791922 , 0.07133405,
        0.        ],
       [0.        , 0.94957647, 0.41511082, 0.07550856, 0.10926986,
        0.        ],
       [0.        , 0.7073071 , 0.72942906, 0.86025751, 0.50540772,
        0.        ],
       [0.        , 0.99370421, 0.88134988, 0.20437282, 0.74077289,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [110]:
#17
0 * np.nan

nan

In [111]:
np.nan == np.nan

False

In [112]:
np.inf > np.nan

False

In [113]:
np.nan - np.nan

nan

In [114]:
np.nan in set([np.nan])

True

In [116]:
0.3 == 3*0.1

False

In [117]:
3*0.1

0.30000000000000004